### ISSUE TITLE
Error when executiing main.py

### ISSUE THREAD

**Issue by iokobi** [billydh/zoom-reporting#1]
Hi @billydh. First thanks for putting this together. Amazing work. Need help as I am getting the error below when I try to run the python script.

`  File "main.py", line 26
    while token := response.json().get("next_page_token"):
                 ^
SyntaxError: invalid syntax`

**Comment by billydh** [comment]
Hi @iokobi , what is your Python version? That operator `:=` is called the Walrus operator and available from Python 3.8+. Refer to the official doc [here](https://docs.python.org/3/whatsnew/3.8.html#assignment-expressions).

**Comment by iokobi** [comment]
Thanks for the quick response @billydh. My python version is 3.6.9. I will make sure to upgrade. Thanks a lot.
